### ISSUE TITLE
Can't override using a named-parameter with an empty hashref

### ISSUE THREAD

**Issue by alnewkirk** [preaction/Beam-Wire#55]
There is a bug in service creation, when the `create_service` method calls the `find_refs` method using overrides in the form of a named-parameter with an empty hashref value. The following example should reproduce the bug.

```perl

# test.pl
use Beam::Wire;

my $wire = Beam::Wire->new(config => { foo => { class => 'Foo' } } );
my $foo  = $wire->get( 'foo', args => { bar => {} } );

```

**Comment by preaction** [comment]
Ouch. This is quite a bit worse: Any empty hashref in a service's `args` would cause this, not just when overriding `get()`. It's just a bit weird/hard to have an empty hashref in the config file, so this has never come up before.

The fix seems simple though, so I'll commit it and push a release tonight. Thanks a lot for the test case!
