### ISSUE TITLE
[bug] Multiple Constructor Methods approach does not work, if class has boolean overloading configured

### ISSUE THREAD

**Issue by XSven** [preaction/Beam-Wire#73]
When I have tried to create an

[URI](https://metacpan.org/pod/URI)

instance using

[Multiple Constructor Methods](https://metacpan.org/pod/distribution/Beam-Wire/lib/Beam/Wire/Help/Config.pod#Multiple-Constructor-Methods)

```
download-url:
  class: URI
  method:
    - method: new
    - method: scheme
      args:
        - http

```
I have got the exception

Can't use string ("URI") as a SCALAR ref while "strict refs" in use at /usr/local/perl-5.14.2_64_8/lib/site_perl/5.14.2/URI.pm line 174.

The Beam::Wire::create_service() method has a problem, if boolean overloading is configured for a class (the URI class does this). I have patched the lines 541 and 543.

```
541             my $invocant = $service // $service_info{class};
543             $service = not(defined($service)) || $return eq 'chain' ? $output
544                      : $service;

```
properly checking “defindness”. I have added

```
subtest 'multiple constructor methods' => sub {
    my $wire = Beam::Wire->new(
        config => {
            uri => {
                class => 'URI',
                method => [
                    {
                        method => 'new',
                    },
                    {
                        method => 'scheme',
                        args => ['http']
                    },
                ],
            },
        },
    );
    isa_ok $wire->get( 'uri' ), 'URI::http';
};

```
to

`t/service/method.t`

Please check.

**Comment by preaction** [comment]
Thanks! Yep, that's definitely a bug. I've made the change you've proposed and added an overload to the existing test. I'll release the new versions shortly.
